#!/usr/bin/env perl

#-- Load modules
use Log::Log4perl "get_logger";
use SCM::Tool::VersionControl::Harvest7;

#-- Initialize log4perl
my $logname = `logname`;
chomp $logname;

Log::Log4perl::init("/var/opt/harvest/usr/$logname/log4perl-$logname.conf");
my $logger = get_logger("SCM");

#-- Instantiate the harvest context

$harctx = SCM::Tool::VersionControl::Harvest7->new();
$harctx->{USERFILE} = "/var/opt/harvest/usr/$logname/.harvest-${logname}.dfo";
$harctx->load(".harvest-global.ctx");
$harctx->load("/var/opt/harvest/usr/$logname/.harvest-$logname.ctx");

$harctx->lock(@ARGV);

$logger->info(`cat hco.log`);
$logger->info(`chmod u+w @ARGV`);

unless (exists $ENV{NOTIDY} ) {
 my @t = `mytidy @ARGV`;

 if ( $? > 0 ) {
    $logger->error( "ERROR: mytidy: ", @t );
 } else {
    $logger->info( "mytidy: ", @t );
 }

}

