#!/usr/bin/env perl

#-- Load modules
use Log::Log4perl "get_logger";
use SCM::Tool::VersionControl::Harvest7;

use Getopt::Long;

my %defines = ();

GetOptions( "define=s" => \%defines)
 or die "usage: mudp [options] <project> <state> <udp process name>";

#-- Initialize log4perl

my $project = shift;
die "usage: mudp [options] <project> <state> <udp process name>" unless $project;

my $state = shift;
die "usage: mudp [options] <project> <state> <udp process name>" unless $state;

my $udp = shift;
die "usage: mudp [options] <project> <state> <udp process name>" unless $udp;

my $logname = `logname`;
chomp $logname;

Log::Log4perl::init("/var/opt/harvest/usr/$logname/log4perl-$logname.conf");
my $logger = get_logger("SCM");

#-- Instantiate the harvest context

$harctx = SCM::Tool::VersionControl::Harvest7->new();
$harctx->{USERFILE} = "/var/opt/harvest/usr/$logname/.harvest-${logname}.dfo";

#$harctx->load( ".harvest-global.ctx");
#$harctx->load( "/var/opt/harvest/usr/$logname/.harvest-$logname.ctx");

$harctx->{BROKER} = 'harprod';
$harctx->{PROJECT} = $project;
$harctx->{STATE} = $state;
$harctx->{PROCESSNAME} = $udp;

print "Executing UDP $harctx->{PROCESSNAME}..\n";
$harctx->ExecUDP(%defines);


