#!/usr/bin/env perl

#-- Load modules
use Log::Log4perl "get_logger";
use SCM::Tool::VersionControl::Harvest7;
use strict;

#-- Initialize log4perl
my $logname = `logname 2>/dev/null`;
$logname = 'har006' if $?;
chomp $logname;

Log::Log4perl::init("/var/opt/harvest/usr/$logname/log4perl-$logname.conf");
my $logger = get_logger("SCM");

#-- Check parms

$logger->logdie("No files supplied.") unless @ARGV;

#-- Instantiate the harvest context

my $harctx = SCM::Tool::VersionControl::Harvest7->new();
$harctx->{USERFILE} = "/var/opt/harvest/usr/$logname/.harvest-${logname}.dfo";
$harctx->load(".harvest-global.ctx");
$harctx->load("/var/opt/harvest/usr/$logname/.harvest-$logname.ctx");

my @files;

foreach my $file ( @ARGV ) {
 push @files, "\"$file\""
}

$harctx->get_and_lock(@files);

unless (exists $ENV{NOTIDY} ) {
my @t = `mytidy @files`;

if ( $? != 0 ) {
    $logger->error( "mytidy: ", @t );
} else {
    $logger->info( "mytidy: ", @t );
}

}
