#!/usr/bin/env perl

#-- Load modules
use Log::Log4perl "get_logger";
use SCM::Tool::VersionControl::Harvest;  #-- uses user and password
use SCM::Tool::VersionControl::Harvest7; #-- uses encrypted password file
use strict;

my $new_project = pop;
my $password = pop;
my $user = pop;

die "usage: mcpj [<user> <password>] <new project>\n"
 unless $new_project;

#-- Initialize log4perl

my $logname;
our $Log4perlLogFile = "$ENV{VISTA}/prod/logs/ctp-harvest-admin.log";
Log::Log4perl::init("$ENV{SHARED_HARUDP}/conf/ctp-log4perl.conf");
my $logger = get_logger("SCM");

unless ( $user and $password ) {
 $logname = `logname`;
 chomp $logname;

}

#-- Instantiate the harvest context

my $harctx;

if ( $user and $password ) {
 $harctx = SCM::Tool::VersionControl::Harvest->new();
 $harctx->{USER} = $user;
 $harctx->{PASSWORD} = $password;

} else {
 $harctx = SCM::Tool::VersionControl::Harvest7->new();
 $harctx->{USERFILE} = "/var/opt/harvest/usr/$logname/.harvest-${logname}.dfo";

}

$harctx->{BROKER}  = "harprod";
$harctx->{PROJECT} = "JBOSS BUILD AND DEPLOY AMFAM APPLICATION TEMPLATE v2";

$logger->info("Creating project $new_project...");
$harctx->CreateProject($new_project );

