#!/usr/bin/env perl

#-- Load modules
use Log::Log4perl "get_logger";
use SCM::Tool::VersionControl::Harvest7; 
use strict;

my $new_repository = pop;
my $password = pop;
my $user = pop;

die "usage: mduprep [<user> <password>] <new repository>\n"
 unless $new_repository;

#-- Initialize log4perl

my $logname;
our $Log4perlLogFile = "$ENV{VISTA}/prod/logs/ctp-harvest-admin.log";
Log::Log4perl::init("$ENV{SHARED_HARUDP}/conf/ctp-log4perl.conf");
my $logger = get_logger("SCM");

unless ( $user and $password ) {
 $logname = `logname`;
 chomp $logname;
}

#-- Instantiate the harvest context

my $harctx;
$harctx = SCM::Tool::VersionControl::Harvest7->new();

if ( $user and $password ) {
 $harctx->{USER} = $user;
 $harctx->{PASSWORD} = $password;

} else {
 $harctx->{USERFILE} = "/var/opt/harvest/usr/$logname/.harvest-${logname}.dfo";

}

$harctx->{BROKER}  = "harprod";
$harctx->{REPOSITORY} = "0_Repository_Template";

$logger->info("Duplicating repository $new_repository from $harctx->{REPOSITORY}...");
$harctx->DuplicateRepository($new_repository );

